// Do not edit this file; automatically generated by build.py.
"use strict";

/*

 SmartFarm hackable glass simulation, built on Google's Blockly

 Copyright 2014 Computing and Information Sciences, Kansas State University.
 http://smartfarm.cis.k-state.edu

 Copyright 2012 Google Inc.
 https://developers.google.com/blockly/

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
Blockly.Elixir=new Blockly.Generator("Elixir");Blockly.Elixir.ORDER_ATOMIC=0;Blockly.Elixir.ORDER_MEMBER=1;Blockly.Elixir.ORDER_NEW=1;Blockly.Elixir.ORDER_FUNCTION_CALL=2;Blockly.Elixir.ORDER_INCREMENT=3;Blockly.Elixir.ORDER_DECREMENT=3;Blockly.Elixir.ORDER_LOGICAL_NOT=4;Blockly.Elixir.ORDER_BITWISE_NOT=4;Blockly.Elixir.ORDER_UNARY_PLUS=4;Blockly.Elixir.ORDER_UNARY_NEGATION=4;Blockly.Elixir.ORDER_TYPEOF=4;Blockly.Elixir.ORDER_VOID=4;Blockly.Elixir.ORDER_DELETE=4;
Blockly.Elixir.ORDER_MULTIPLICATION=5;Blockly.Elixir.ORDER_DIVISION=5;Blockly.Elixir.ORDER_MODULUS=5;Blockly.Elixir.ORDER_ADDITION=6;Blockly.Elixir.ORDER_SUBTRACTION=6;Blockly.Elixir.ORDER_BITWISE_SHIFT=7;Blockly.Elixir.ORDER_RELATIONAL=8;Blockly.Elixir.ORDER_IN=8;Blockly.Elixir.ORDER_INSTANCEOF=8;Blockly.Elixir.ORDER_EQUALITY=9;Blockly.Elixir.ORDER_BITWISE_AND=10;Blockly.Elixir.ORDER_BITWISE_XOR=11;Blockly.Elixir.ORDER_BITWISE_OR=12;Blockly.Elixir.ORDER_LOGICAL_AND=13;
Blockly.Elixir.ORDER_LOGICAL_OR=14;Blockly.Elixir.ORDER_CONDITIONAL=15;Blockly.Elixir.ORDER_ASSIGNMENT=16;Blockly.Elixir.ORDER_COMMA=17;Blockly.Elixir.ORDER_NONE=99;Blockly.Elixir.init=function(a){Blockly.Elixir.definitions_=Object.create(null);Blockly.Elixir.functionNames_=Object.create(null);Blockly.Elixir.variableDB_?Blockly.Elixir.variableDB_.reset():Blockly.Elixir.variableDB_=new Blockly.Names(Blockly.Elixir.RESERVED_WORDS_)};
Blockly.Elixir.finish=function(a){return":random.seed(:os.timestamp)\n\n"+a};Blockly.Elixir.scrubNakedValue=function(a){return a+"\n"};Blockly.Elixir.quote_=function(a){a=a.replace(/\\/g,"\\\\").replace(/\n/g,"\\\n").replace(/'/g,"\\'");return"'"+a+"'"};
Blockly.Elixir.scrub_=function(a,b){var c="";if(!a.outputConnection||!a.outputConnection.targetConnection){var d=a.getCommentText();d&&(c+=Blockly.Elixir.prefixLines(d,"# ")+"\n");for(var e=0;e<a.inputList.length;e++)a.inputList[e].type==Blockly.INPUT_VALUE&&(d=a.inputList[e].connection.targetBlock())&&(d=Blockly.Elixir.allNestedComments(d))&&(c+=Blockly.Elixir.prefixLines(d,"# "))}e=a.nextConnection&&a.nextConnection.targetBlock();e=Blockly.Elixir.blockToCode(e);return c+b+e};/*

 SmartFarm hackable glass simulation, built on Google's Blockly

 Copyright 2014 Computing and Information Sciences, Kansas State University.
 http://smartfarm.cis.k-state.edu

 Copyright 2012 Google Inc.
 https://developers.google.com/blockly/

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
Blockly.Elixir.math={};Blockly.Elixir.math_number=function(a){return[parseFloat(a.getFieldValue("NUM")),Blockly.Elixir.ORDER_ATOMIC]};
Blockly.Elixir.math_arithmetic=function(a){var b={ADD:[" + ",Blockly.Elixir.ORDER_ADDITION],MINUS:[" - ",Blockly.Elixir.ORDER_SUBTRACTION],MULTIPLY:[" * ",Blockly.Elixir.ORDER_MULTIPLICATION],DIVIDE:[" / ",Blockly.Elixir.ORDER_DIVISION],POWER:[null,Blockly.Elixir.ORDER_COMMA]}[a.getFieldValue("OP")],c=b[0],b=b[1],d=Blockly.Elixir.valueToCode(a,"A",b)||"0";a=Blockly.Elixir.valueToCode(a,"B",b)||"0";return c?[d+c+a,b]:[":math.pow("+d+", "+a+")",Blockly.Elixir.ORDER_FUNCTION_CALL]};
Blockly.Elixir.math_single=function(a){var b=a.getFieldValue("OP"),c;if("NEG"==b)return a=Blockly.Elixir.valueToCode(a,"NUM",Blockly.Elixir.ORDER_UNARY_NEGATION)||"0","-"==a[0]&&(a=" "+a),["-"+a,Blockly.Elixir.ORDER_UNARY_NEGATION];a="SIN"==b||"COS"==b||"TAN"==b?Blockly.Elixir.valueToCode(a,"NUM",Blockly.Elixir.ORDER_DIVISION)||"0":Blockly.Elixir.valueToCode(a,"NUM",Blockly.Elixir.ORDER_NONE)||"0";switch(b){case "ABS":c="abs("+a+")";break;case "ROOT":c=":math.sqrt("+a+")";break;case "LN":c=":math.log("+
a+")";break;case "LOG10":c=":math.log10("+a+")";break;case "EXP":c=":math.exp("+a+")";break;case "POW10":c=":math.pow(10,"+a+")";break;case "ROUND":c="round("+a+")";break;case "ROUNDUP":c="round(("+a+" + 0.5))";break;case "ROUNDDOWN":c="round(("+a+" - 0.5))";break;case "SIN":c="Float.round(:math.sin("+a+" / 180.0 * :math.pi),15)";break;case "COS":c="Float.round(:math.cos("+a+" / 180.0 * :math.pi),15)";break;case "TAN":c=":math.tan("+a+" / 180.0 * :math.pi)"}if(c)return[c,Blockly.Elixir.ORDER_FUNCTION_CALL];
switch(b){case "ASIN":c=":math.asin("+a+") / :math.PI * 180.0";break;case "ACOS":c=":math.acos("+a+") / :math.pi * 180.0";break;case "ATAN":c=":math.atan("+a+") / :math.pi * 180.0";break;default:throw"Unknown math operator: "+b;}return[c,Blockly.Elixir.ORDER_DIVISION]};
Blockly.Elixir.math_constant=function(a){return{PI:[":math.pi",Blockly.Elixir.ORDER_MEMBER],E:["2.718281828459045",Blockly.Elixir.ORDER_MEMBER],GOLDEN_RATIO:["(1 + :math.sqrt(5)) / 2",Blockly.Elixir.ORDER_DIVISION],SQRT2:["1.4142135623730951",Blockly.Elixir.ORDER_MEMBER],SQRT1_2:["0.7071067811865476",Blockly.Elixir.ORDER_MEMBER]}[a.getFieldValue("CONSTANT")]};
Blockly.Elixir.math_number_property=function(a){var b=Blockly.Elixir.valueToCode(a,"NUMBER_TO_CHECK",Blockly.Elixir.ORDER_MODULUS)||"0",c=a.getFieldValue("PROPERTY"),d;if("PRIME"==c)return d=Blockly.Elixir.provideFunction_("math_isPrime",["function "+Blockly.Elixir.FUNCTION_NAME_PLACEHOLDER_+"(n) {","  // https://en.wikipedia.org/wiki/Primality_test#Naive_methods","  if (n == 2 || n == 3) {","    return true;","  }","  // False if n is NaN, negative, is 1, or not whole.","  // And false if n is divisible by 2 or 3.",
"  if (isNaN(n) || n <= 1 || n % 1 != 0 || n % 2 == 0 || n % 3 == 0) {","    return false;","  }","  // Check all the numbers of form 6k +/- 1, up to sqrt(n).","  for (var x = 6; x <= Math.sqrt(n) + 1; x += 6) {","    if (n % (x - 1) == 0 || n % (x + 1) == 0) {","      return false;","    }","  }","  return true;","}"])+"("+b+")",[d,Blockly.Elixir.ORDER_FUNCTION_CALL];switch(c){case "EVEN":d=b+" % 2 == 0";break;case "ODD":d=b+" % 2 == 1";break;case "WHOLE":d=b+" % 1 == 0";break;case "POSITIVE":d=
b+" > 0";break;case "NEGATIVE":d=b+" < 0";break;case "DIVISIBLE_BY":a=Blockly.Elixir.valueToCode(a,"DIVISOR",Blockly.Elixir.ORDER_MODULUS)||"0",d=b+" % "+a+" == 0"}return[d,Blockly.Elixir.ORDER_EQUALITY]};Blockly.Elixir.math_change=function(a){var b=Blockly.Elixir.valueToCode(a,"DELTA",Blockly.Elixir.ORDER_ADDITION)||"0";a=Blockly.Elixir.variableDB_.getName(a.getFieldValue("VAR"),Blockly.Variables.NAME_TYPE);return a+" = (typeof "+a+" == 'number' ? "+a+" : 0) + "+b+";\n"};
Blockly.Elixir.math_round=Blockly.Elixir.math_single;Blockly.Elixir.math_trig=Blockly.Elixir.math_single;
Blockly.Elixir.math_on_list=function(a){var b=a.getFieldValue("OP");switch(b){case "SUM":a=Blockly.Elixir.valueToCode(a,"LIST",Blockly.Elixir.ORDER_MEMBER)||"[]";a+=".reduce(function(x, y) {return x + y;})";break;case "MIN":a=Blockly.Elixir.valueToCode(a,"LIST",Blockly.Elixir.ORDER_COMMA)||"[]";a="Math.min.apply(null, "+a+")";break;case "MAX":a=Blockly.Elixir.valueToCode(a,"LIST",Blockly.Elixir.ORDER_COMMA)||"[]";a="Math.max.apply(null, "+a+")";break;case "AVERAGE":b=Blockly.Elixir.provideFunction_("math_mean",
["function "+Blockly.Elixir.FUNCTION_NAME_PLACEHOLDER_+"(myList) {","  return myList.reduce(function(x, y) {return x + y;}) / myList.length;","}"]);a=Blockly.Elixir.valueToCode(a,"LIST",Blockly.Elixir.ORDER_NONE)||"[]";a=b+"("+a+")";break;case "MEDIAN":b=Blockly.Elixir.provideFunction_("math_median",["function "+Blockly.Elixir.FUNCTION_NAME_PLACEHOLDER_+"(myList) {","  var localList = myList.filter(function (x) {return typeof x == 'number';});","  if (!localList.length) return null;","  localList.sort(function(a, b) {return b - a;});",
"  if (localList.length % 2 == 0) {","    return (localList[localList.length / 2 - 1] + localList[localList.length / 2]) / 2;","  } else {","    return localList[(localList.length - 1) / 2];","  }","}"]);a=Blockly.Elixir.valueToCode(a,"LIST",Blockly.Elixir.ORDER_NONE)||"[]";a=b+"("+a+")";break;case "MODE":b=Blockly.Elixir.provideFunction_("math_modes",["function "+Blockly.Elixir.FUNCTION_NAME_PLACEHOLDER_+"(values) {","  var modes = [];","  var counts = [];","  var maxCount = 0;","  for (var i = 0; i < values.length; i++) {",
"    var value = values[i];","    var found = false;","    var thisCount;","    for (var j = 0; j < counts.length; j++) {","      if (counts[j][0] === value) {","        thisCount = ++counts[j][1];","        found = true;","        break;","      }","    }","    if (!found) {","      counts.push([value, 1]);","      thisCount = 1;","    }","    maxCount = Math.max(thisCount, maxCount);","  }","  for (var j = 0; j < counts.length; j++) {","    if (counts[j][1] == maxCount) {","        modes.push(counts[j][0]);",
"    }","  }","  return modes;","}"]);a=Blockly.Elixir.valueToCode(a,"LIST",Blockly.Elixir.ORDER_NONE)||"[]";a=b+"("+a+")";break;case "STD_DEV":b=Blockly.Elixir.provideFunction_("math_standard_deviation",["function "+Blockly.Elixir.FUNCTION_NAME_PLACEHOLDER_+"(numbers) {","  var n = numbers.length;","  if (!n) return null;","  var mean = numbers.reduce(function(x, y) {return x + y;}) / n;","  var variance = 0;","  for (var j = 0; j < n; j++) {","    variance += Math.pow(numbers[j] - mean, 2);","  }",
"  variance = variance / n;","  return Math.sqrt(variance);","}"]);a=Blockly.Elixir.valueToCode(a,"LIST",Blockly.Elixir.ORDER_NONE)||"[]";a=b+"("+a+")";break;case "RANDOM":b=Blockly.Elixir.provideFunction_("math_random_list",["function "+Blockly.Elixir.FUNCTION_NAME_PLACEHOLDER_+"(list) {","  var x = Math.floor(Math.random() * list.length);","  return list[x];","}"]);a=Blockly.Elixir.valueToCode(a,"LIST",Blockly.Elixir.ORDER_NONE)||"[]";a=b+"("+a+")";break;default:throw"Unknown operator: "+b;}return[a,
Blockly.Elixir.ORDER_FUNCTION_CALL]};Blockly.Elixir.math_modulo=function(a){var b=Blockly.Elixir.valueToCode(a,"DIVIDEND",Blockly.Elixir.ORDER_MODULUS)||"0";a=Blockly.Elixir.valueToCode(a,"DIVISOR",Blockly.Elixir.ORDER_MODULUS)||"0";return[b+" % "+a,Blockly.Elixir.ORDER_MODULUS]};
Blockly.Elixir.math_constrain=function(a){var b=Blockly.Elixir.valueToCode(a,"VALUE",Blockly.Elixir.ORDER_COMMA)||"0",c=Blockly.Elixir.valueToCode(a,"LOW",Blockly.Elixir.ORDER_COMMA)||"0";Blockly.Elixir.valueToCode(a,"HIGH",Blockly.Elixir.ORDER_COMMA);return["Enum.min([Enum.max(["+b+", "+c+"]),"+arguement2+"])",Blockly.Elixir.ORDER_FUNCTION_CALL]};
Blockly.Elixir.math_random_int=function(a){var b=Blockly.Elixir.valueToCode(a,"FROM",Blockly.Elixir.ORDER_COMMA)||"0";a=Blockly.Elixir.valueToCode(a,"TO",Blockly.Elixir.ORDER_COMMA)||"0";return[b+" + :random.uniform("+a+" - "+b+")",Blockly.Elixir.ORDER_FUNCTION_CALL]};Blockly.Elixir.math_random_float=function(a){return[":random.uniform()",Blockly.Elixir.ORDER_FUNCTION_CALL]};/*

 SmartFarm hackable glass simulation, built on Google's Blockly

 Copyright 2015 Computing and Information Sciences, Kansas State University.
 http://smartfarm.cis.k-state.edu

 Copyright 2012 Google Inc.
 https://developers.google.com/blockly/

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
Blockly.Elixir.lsystems={};Blockly.Elixir.addReservedWords("svg_path");Blockly.Elixir.lsystems_draw=function(a){var b=Blockly.Elixir.valueToCode(a,"LSYSTEM",Blockly.Elixir.ORDER_ATOMIC)||'{:lsystem, <<"">>, []}',c=Blockly.Elixir.valueToCode(a,"TIMES",Blockly.Elixir.ORDER_ATOMIC)||"0",d=Blockly.Elixir.valueToCode(a,"ANGLE",Blockly.Elixir.ORDER_ATOMIC)||"0";a=Blockly.Elixir.valueToCode(a,"DISTANCE",Blockly.Elixir.ORDER_ATOMIC)||"0";return"svg_path = LSystem.render("+b+", "+c+", "+d+", "+a+")\n"};
Blockly.Elixir.lsystems_create=function(a){for(var b=a.getFieldValue("AXIOM")||"",c=Array(a.itemCount_+1),d=0;d<a.itemCount_;d++)c[d]=Blockly.Elixir.valueToCode(a,"ADD"+d,Blockly.Elixir.ORDER_ATOMIC)||"";c[a.itemCount_]="<<symbol,tail::binary>> -> {<<symbol>>,tail}";c='{:lsystem, <<"'+b+'">>, fn '+c.join("; ")+" end}";return[c,Blockly.Elixir.ORDER_ATOMIC]};
Blockly.Elixir.lsystems_rule=function(a){var b=a.getFieldValue("MATCH")||"0";a=a.getFieldValue("YIELD")||"0";return['<<"'+b+'",tail::binary>> -> {<<"'+a+'">>,tail}',Blockly.Elixir.ORDER_ATOMIC]};
// Copyright 2012 Google Inc.  Apache License 2.0
Blockly.Elixir.variables={};Blockly.Elixir.variables_get=function(a){return[Blockly.Elixir.variableDB_.getName(a.getFieldValue("VAR"),Blockly.Variables.NAME_TYPE),Blockly.Elixir.ORDER_ATOMIC]};Blockly.Elixir.variables_set=function(a){var b=Blockly.Elixir.valueToCode(a,"VALUE",Blockly.Elixir.ORDER_ASSIGNMENT)||"0";return Blockly.Elixir.variableDB_.getName(a.getFieldValue("VAR"),Blockly.Variables.NAME_TYPE)+" = "+b+"\n"};/*

 SmartFarm hackable glass simulation, built on Google's Blockly

 Copyright 2014 Computing and Information Sciences, Kansas State University.
 http://smartfarm.cis.k-state.edu

 Copyright 2012 Google Inc.
 https://developers.google.com/blockly/

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
Blockly.Elixir.addReservedWords("weather_rainfall","weather_snowfall","weather_solar_radiation","weather_average_temperature","weather_high_temperature","weather_low_temperature","weather_wind_speed","weather_wind_direction","weather_dew_point","weather_relative_humidity");
Blockly.Elixir.weather_set_precipitation=function(a){var b=Blockly.Elixir.valueToCode(a,"PRECIPITATION",Blockly.Elixir.ORDER_ATOMIC)||"0",c=a.getFieldValue("MEASURE");a=a.getFieldValue("FORM");"INCHES"==c&&(b="(("+b+") * 25.4)");switch(a){case "RAIN":return"weather_rainfall = "+b+"\n";case "SNOW":return"weather_snowfall="+b+"\n"}return""};
Blockly.Elixir.weather_get_precipitation=function(a){var b=a.getFieldValue("MEASURE"),c="0";switch(a.getFieldValue("FORM")){case "RAIN":c="weather_rainfall";break;case "SNOW":c="weather_snowfall"}"INCHES"==b&&(c="(("+c+") / 25.4)");return[c,Blockly.Elixir.ORDER_ATOMIC]};
Blockly.Elixir.weather_set_solar_radiation=function(a){var b=Blockly.Elixir.valueToCode(a,"RADIATION",Blockly.Elixir.ORDER_ATOMIC)||"0";"LANGLEY"==a.getFieldValue("UNIT")&&(b="(("+b+") * 41840)");return"weather_solar_radiation = "+b+"\n"};Blockly.Elixir.weather_get_solar_radiation=function(a){var b="weather_solar_radiation";"LANGLEY"==a.getFieldValue("UNIT")&&(b="(("+b+") / 41840)");return[b,Blockly.Elixir.ORDER_ATOMIC]};
Blockly.Elixir.weather_set_temperature=function(a){var b=Blockly.Elixir.valueToCode(a,"TEMP",Blockly.Elixir.ORDER_ATOMIC)||"0",c=a.getFieldValue("MEASURE");a=a.getFieldValue("CATEGORY");"DEGREES_F"==c&&(b="((("+b+") - 32) * (5/9))");switch(a){case "AVERAGE":return"weather_average_temperature="+b+"\n";case "HIGH":return"weather_high_temperature="+b+"\n";case "LOW":return"weather_low_temperature="+b+"\n"}return""};
Blockly.Elixir.weather_get_temperature=function(a){var b=a.getFieldValue("MEASURE"),c="0";switch(a.getFieldValue("CATEGORY")){case "AVERAGE":c="weather_average_temperature";break;case "HIGH":c="weather_high_temperature";break;case "LOW":c="weather_low_temperature"}"DEGREES_F"==b&&(c="("+c+"*9/5+32)");return[c,Blockly.Elixir.ORDER_ATOMIC]};
Blockly.Elixir.weather_set_wind_speed=function(a){var b=Blockly.Elixir.valueToCode(a,"SPEED",Blockly.Elixir.ORDER_ATOMIC)||"0";"MILES_PER_HOUR"==a.getFieldValue("MEASURE")&&(b="("+b+"*0.44704)");return"weather_wind_speed="+b+"\n"};Blockly.Elixir.weather_get_wind_speed=function(a){var b="weather_wind_speed";"MILES_PER_HOUR"==a.getFieldValue("MEASURE")&&(b="("+b+"/0.44704)");return[b,Blockly.Elixir.ORDER_ATOMIC]};
Blockly.Elixir.weather_set_wind_direction=function(a){return"weather_wind_direction="+(Blockly.Elixir.valueToCode(a,"DIRECTION",Blockly.Elixir.ORDER_ATOMIC)||"0")+"\n"};Blockly.Elixir.weather_get_wind_direction=function(a){return["weather_wind_direction",Blockly.Elixir.ORDER_ATOMIC]};Blockly.Elixir.weather_get_dew_point=function(a){a=a.getFieldValue("UNIT");code="weather_dew_point";"DEGREES_F"==a&&(code="("+code+"*9/5+32)");return[code,Blockly.Elixir.ORDER_ATOMIC]};
Blockly.Elixir.weather_set_relative_humidity=function(a){return"weather_relative_humidity="+(Blockly.Elixir.valueToCode(a,"RELATIVE_HUMIDITY",Blockly.Elixir.ORDER_ATOMIC)||"0")+"\n"};Blockly.Elixir.weather_get_relative_humidity=function(a){return["weather_relative_humidity",Blockly.Elixir.ORDER_ATOMIC]};